services:
  - type: web
    name: translator-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: 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
        sync: false
